name: Ansible check
on:
  workflow_dispatch:
    inputs:
      variable_test:
        description: 'Type a string'
        type: string
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Cheking if ansible is present 
        run: ansible --version
  job_name_install_check_ansible:
   runs-on: ubuntu-latest
   needs: check
   steps:
    - name: Installing Ansible
      shell: bash
      run: sudo apt update;sudo apt install software-properties-common;sudo add-apt-repository --yes --update ppa:ansible/ansible;sudo apt install ansible
  checking_ansible_version:
    runs-on: ubuntu-latest
    needs: job_name_install_check_ansible
    steps:
      - name: Checking Ansible Version
        shell: bash
        run: ansible --version