name: First Workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: true
        type: string
      testvariable:
        description: 'A string input'
        required: false
        type: string
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
       - name: Printing variables
         shell: bash
         run: echo ${{ inputs.testvariable}}
       - name: Printing uptime and hostname
         shell: bash
         run: uptime;hostname